[package]
name = "nature-of-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18.1"

[[example]]
name = "i_1_random_walk"
path = "ch01-vectors/i_1_random_walk.rs"